
spring:
  datasource:
    url: jdbc:h2:mem:testfood
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
